spring:
  data:
    mongodb:
      uri: mongodb+srv://<username>:<db_password>@cluster0.xxxxx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journalDB
      auto-index-creation: true
    redis:
      host: redis-xxxx.xxxx.xx-xxxx-1-1.ec2.redns.redis-cloud.com
      port: 13698
      password: xxxxxxxxxxx
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: xxxx xxxx xxxx xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

weather:
  api:
    key: xxxxxxxxxxxxxxxx

logging:
  level:
    com:
      project: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG

