jwt:
  secret:
    key: ${JWT_SECRET}

weather:
  api:
    key: ${WEATHER_API_KEY}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: journalDB
      auto-index-creation: true
    redis:
      host: ${REDIS_URI}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    com:
      project: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG